services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: bhcon_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: bhasaconnect_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d bhasaconnect_dev"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bhcon_be
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://dev_user:dev_password@db:5432/bhasaconnect_dev
      SECRET_KEY: dev_secret_key_not_for_production_use_only
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440
      CLOUDINARY_CLOUD_NAME: your_cloudinary_cloud_name
      CLOUDINARY_API_KEY: your_cloudinary_api_key
      CLOUDINARY_API_SECRET: your_cloudinary_api_secret
      ENVIRONMENT: development
      DEBUG: "true"
      CORS_ORIGINS: "http://localhost:3000,http://localhost:5173,http://frontend:3000"
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 5 &&
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Starting development server with hot reload...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Frontend React App - Development with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bhcon_fe
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_CLOUDINARY_CLOUD_NAME: your_cloudinary_cloud_name
      VITE_APP_TITLE: Bhasa Con (Dev)
      VITE_DEBUG: "true"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Anonymous volume for node_modules
    ports:
      - "3000:5173"
    networks:
      - app-network
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0 --port 5173

volumes:
  postgres_data:
    driver: local
  backend_uploads:
    driver: local

networks:
  app-network:
    driver: bridge
