version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: bhasaconnect_db_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: bhasaconnect_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    networks:
      - dev-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d bhasaconnect_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API (Development with hot reload)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bhasaconnect_backend_dev
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://dev_user:dev_password@db:5432/bhasaconnect_dev
      SECRET_KEY: dev_secret_key_not_for_production
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 1440  # 24 hours for dev
      CLOUDINARY_CLOUD_NAME: your_cloudinary_cloud_name
      CLOUDINARY_API_KEY: your_cloudinary_api_key
      CLOUDINARY_API_SECRET: your_cloudinary_api_secret
      ENVIRONMENT: development
      DEBUG: "true"
      CORS_ORIGINS: "http://localhost:3000,http://localhost:5173"
    volumes:
      - ./backend:/app
      - backend_dev_uploads:/app/uploads
    ports:
      - "8000:8000"
    networks:
      - dev-network
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        echo 'Waiting for database...' &&
        sleep 3 &&
        echo 'Running database migrations...' &&
        alembic upgrade head &&
        echo 'Starting development server with hot reload...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      "

  # Frontend (Development with hot reload using Vite dev server)
  frontend-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: bhasaconnect_frontend_dev
    restart: unless-stopped
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_CLOUDINARY_CLOUD_NAME: your_cloudinary_cloud_name
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Anonymous volume for node_modules
    ports:
      - "3000:5173"
    networks:
      - dev-network
    depends_on:
      - backend
    command: npm run dev -- --host 0.0.0.0 --port 5173

  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: bhasaconnect_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - dev-network
    command: redis-server --appendonly yes

volumes:
  postgres_dev_data:
    driver: local
  backend_dev_uploads:
    driver: local

networks:
  dev-network:
    driver: bridge
