version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_APP_TITLE=Bhasa Con
    depends_on:
      - backend
    networks:
      - bhasa-con-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///./bhasa_con.db
    networks:
      - bhasa-con-network

networks:
  bhasa-con-network:
    driver: bridge